src/main/java/br/com/casadocodigo/loja/models/CarrinhoCompras.java
package br.com.casadocodigo.loja.models;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.Map;

import org.springframework.context.annotation.Scope;
import org.springframework.context.annotation.ScopedProxyMode;
import org.springframework.stereotype.Component;
import org.springframework.web.context.WebApplicationContext;

@Component
@Scope(value = WebApplicationContext.SCOPE_SESSION, proxyMode = ScopedProxyMode.TARGET_CLASS)
public class CarrinhoCompras implements Serializable{

	private Map<CarrinhoItem, Integer> itens = new LinkedHashMap<CarrinhoItem, Integer>();

	public void add(CarrinhoItem item) {
		itens.put(item, getQuantidade(item) + 1);
	}

	private int getQuantidade(CarrinhoItem item) {

		if (!itens.containsKey(item)) {
			itens.put(item, 0);
		}

		return itens.get(item);
	}

	public int getQuantidade() {
		return itens.values().stream().reduce(0, (proximo, acumulador) -> proximo + acumulador);
	}

	public Collection<CarrinhoItem> getItens() {
		return itens.keySet();
	}

	public BigDecimal getTotal(CarrinhoItem item) {
		return item.getTotal(getQuantidade(item));
	}

	public BigDecimal getTotal() {
		BigDecimal total = BigDecimal.ZERO;

		for (CarrinhoItem item : itens.keySet()) {
			total = total.add(getTotal(item));
		}
		return total;
	}
	
	public void remover (Integer produtoId, TipoPreco tipoPreco) {
		Produto produto = new Produto();
		produto.setId(produtoId);
		itens.remove(new CarrinhoItem(produto, tipoPreco));
	}

}

src/main/java/br/com/casadocodigo/loja/controllers/HomeController.java
package br.com.casadocodigo.loja.controllers;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;

import br.com.casadocodigo.loja.daos.ProdutoDAO;
import br.com.casadocodigo.loja.daos.UsuarioDAO;
import br.com.casadocodigo.loja.models.Produto;
import br.com.casadocodigo.loja.models.Role;
import br.com.casadocodigo.loja.models.Usuario;

@Controller
@RequestMapping("/")
public class HomeController {

	@Autowired
	ProdutoDAO produtoDAO;
	
	@Autowired
	private UsuarioDAO usuarioDao;

	@Transactional
	@ResponseBody
	@RequestMapping("/url-magica-maluca-oajksfbvad6584i57j54f9684nvi658efnoewfmnvowefnoeijn")
	public String urlMagicaMaluca() {
		Usuario usuario = new Usuario();
		usuario.setNome("Admin");
		usuario.setEmail("admin@casadocodigo.com.br");
		usuario.setSenha("$2a$10$lt7pS7Kxxe5JfP.vjLNSyOXP11eHgh7RoPxo5fvvbMCZkCUss2DGu");
		usuario.setRoles(Arrays.asList(new Role("ROLE_ADMIN")));

		usuarioDao.gravar(usuario);

		return "Url Mágica executada";
	}

	@Cacheable(value = "produtosHome")
	@RequestMapping(value = "/", method = RequestMethod.GET)
	public ModelAndView index() {
		System.out.println("Exibindo a home do CDC...");

		List<Produto> produtos = new ArrayList<>();
		produtos = produtoDAO.listar();

		ModelAndView modelAndView = new ModelAndView("home");

		modelAndView.addObject("produtos", produtos);

		return modelAndView;
	}

}

src/main/java/br/com/casadocodigo/loja/controllers/LoginController.java
package br.com.casadocodigo.loja.controllers;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Controller
public class LoginController {

	@RequestMapping(value = "/login", method = RequestMethod.GET)
	public String loginForm() {
		return "loginForm";
	}
	
}

src/main/webapp/WEB-INF/views/cabecalho.jsp
	<header id="layout-header">
		<div class="clearfix container">
			<a href="/" id="logo"> </a>
			<div id="header-content">
				<nav id="main-nav">

					<ul class="clearfix">
						<li><a href="${s:mvcUrl('CCC#itens').build() }" rel="nofollow">
						 <s:message code="menu.carrinho" arguments="${carrinhoCompras.quantidade}"/></a></li>
						<li><a href="/pages/sobre-a-casa-do-codigo" rel="nofollow">
						<s:message code="menu.sobre" /></a></li>
						<li><a href="?locale=pt" rel="nofollow">
						<s:message code="menu.pt" /></a></li>
 						<li><a href="?locale=en_US" rel="nofollow">
						<s:message code="menu.en" /></a></li>
<!-- 					
<!-- 						<li><a href="/pages/perguntas-frequentes" rel="nofollow">Perguntas -->
<!-- 								Frequentes</a></li> -->
					</ul>
				</nav>
			</div>
		</div>
	</header>
	
	<nav class="categories-nav">
		<ul class="container">
			<li class="category"><a href="http://www.casadocodigo.com.br">
				<s:message code="navegacao.categoria.home" /> </a></li>
			<li class="category"><a href="/collections/livros-de-agile">
				<s:message code="navegacao.categoria.agile" /> </a></li>
			<li class="category"><a href="/collections/livros-de-front-end">
				<s:message code="navegacao.categoria.front_end" /> </a></li>
			<li class="category"><a href="/collections/livros-de-games">
				<s:message code="navegacao.categoria.games" /> </a></li>
			<li class="category"><a href="/collections/livros-de-java">
				<s:message code="navegacao.categoria.java" /> </a></li>
			<li class="category"><a href="/collections/livros-de-mobile">
				<s:message code="navegacao.categoria.mobile" /> </a></li>
			<li class="category"><a	href="/collections/livros-desenvolvimento-web">
				<s:message code="navegacao.categoria.web" /> </a></li>
			<li class="category"><a href="/collections/outros">
			 	<s:message code="navegacao.categoria.outros" /> </a></li>
		</ul>
	</nav>

src/main/webapp/WEB-INF/views/error.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib tagdir="/WEB-INF/tags" prefix="tags" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s" %>
<%@ taglib uri="http://www.springframework.org/security/tags" prefix="security" %>

<tags:pageTemplate titulo="Erro genérico!">

	<section id="index-section" class="container middle">
		<h2>O produto informado não foi encontrado!</h2>
	</section>

</tags:pageTemplate>

src/main/webapp/WEB-INF/views/home.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib tagdir="/WEB-INF/tags" prefix="tags" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s" %>
<%@ taglib uri="http://www.springframework.org/security/tags" prefix="security" %>

<tags:pageTemplate titulo="Livros de Java, Android, iOS, Mobile e muito mais...">

	<section id="index-section" class="container middle">
		<h1 class="cdc-call">Últimos dias com os preços promocionais.
			Aproveite!</h1>

		<ul class="clearfix book-collection">

			<c:forEach items="${produtos}" var="produto">

				<li><a
					href="${s:mvcUrl('PC#detalhe').arg(0, produto.id).build() }"
					class="block clearfix">
						<h2 class="product-title">${produto.titulo}</h2> <img width="143"
						height="202"
						src="https://cdn.shopify.com/s/files/1/0155/7645/products/java8-featured_large.png?v=1411490181"
						alt="Java 8 Prático" title="Java 8 Prático" /> <small
						class="buy-button">Compre</small>
				</a></li>
			</c:forEach>
			<!-- FIM DO c:forEach -->

		</ul>

		<h2 class="cdc-call">Diferenciais da Casa do Código</h2>

		<ul id="cdc-diferenciais" class="clearfix">
			<li class="col-left">
				<h3>E-books sem DRM. Leia onde quiser</h3>
				<p>
					<span class="sprite" id="sprite-drm"></span> Nossos e-books não
					possuem DRM, ou seja, você pode ler em qualquer computador, tablet
					e smartphone.
				</p>
			</li>
			<li class="col-right">
				<h3>Autores de renome na comunidade</h3>
				<p>
					<span class="sprite" id="sprite-renome"></span> Autores que
					participam ativamente na comunidade com Open Source, listas de
					discussão, grupos e mais.
				</p>
			</li>
			<li class="col-left">
				<h3>Receba atualizações dos e-books</h3>
				<p>
					<span class="sprite" id="sprite-atualizacoes"></span> Quando você
					compra um e-book, automaticamente tem direito às atualizações e
					correções dele.
				</p>
			</li>
			<li class="col-right">
				<h3>Livros com curadoria da Caelum</h3>
				<p>
					<span class="sprite" id="sprite-caelum"></span> Desenvolvedores
					experientes que avaliam e revisam os livros constantemente.
				</p>
			</li>
		</ul>
	</section>

</tags:pageTemplate>

src/main/webapp/WEB-INF/views/loginForm.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s"%>


<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Livros de Java, Android, iPhone, Ruby, PHP e muito mais -
	Casa do Código</title>
<c:url value="/resources/css" var="cssPath" />
<link rel="stylesheet" href="${cssPath}/bootstrap.min.css" />
<link rel="stylesheet" href="${cssPath}/bootstrap-theme.min.css" />
<style type="text/css">
body {
	padding: 60px 0px;
}
</style>
</head>
<body>

	<div class="container">

		<h1>Login Casa do Código</h1>

		<form:form servletRelativeAction="/login" method="post">
			<div class="form-group">
				<label>Usuário</label> <input type="text" name="username"
					class="form-control">
			</div>

			<div class="form-group">
				<label>Senha</label> <input type="password" name="password"
					class="form-control">
			</div>

			<button type="submit" class="btn btn-primary">Entrar</button>

		</form:form>

	</div>

</body>
</html>